import './globals.css'
import {poppins} from './fonts/poppins'

export const metadata = {
  title: 'task',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
